---
- name: Prepare Molecule containers
  hosts: molecule
  gather_facts: false

  tasks:
    - name: Install Python on Ubuntu
      ansible.builtin.raw: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y python3 ca-certificates tar gzip
      changed_when: false
      when: inventory_hostname == "molecule-ubuntu"

    - name: Install Python 3.11 on Oracle Linux 8
      ansible.builtin.raw: |
        dnf install -y python3.11 ca-certificates tar gzip
      changed_when: false
      when: inventory_hostname == "molecule-oraclelinux8"